/*
 * prove.c -- Gate Frama-C Eva (D3.1, P7): --prove -> L2 PROVEN.
 *
 * Alur (pola sama dengan run.c / clang P6):
 *   1. Cari wsl.exe (PATH). Tidak ada -> skip, assurance statis + diagnostic.
 *   2. Deteksi frama-c di dalam WSL (`command -v frama-c`). Tidak ada ->
 *      skip, assurance statis + diagnostic (non-blocking).
 *   3. Jalankan `frama-c -eva <file>` dengan source dikirim via stdin ke
 *      template bash tetap (tidak pernah jadi argumen proses Windows).
 *   4. Parse output:
 *        - baris [eva:alarm] -> alarm RTE -> MC_PROVE_VIOLATION (bug pasti,
 *          kelas RTE, sesuai rencana D3.1).
 *        - "0 alarms generated by the analysis." -> bersih -> caller naikkan
 *          ke L2 (PROVEN).
 *        - exit != 0 / gagal parse -> skip (bukan bukti bug), assurance statis.
 *
 * Catatan jujur: Eva sound untuk kelas RTE (tidak ada false-negative pada
 * jalur yang dieksplorasi), tapi analisisnya berjalan pada fungsi yang
 * terjangkau dari main (whole program analysis). Baris alarm dipakai sebagai
 * bukti potensi bug memori.
 */
#include "prove.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "gate.h"
#include "proc.h"

/* Template tetap yang dijalankan di dalam WSL. Source mengalir via stdin
 * (cat > $t); nama file sementara memakai $$ (pid shell WSL). */
#define WSL_PROVE_CMD \
    "t=/tmp/myc_prove_$$.c; cat > $t; " \
    "eval $(opam env) 2>/dev/null; " \
    "frama-c -eva $t; rc=$?; rm -f $t; exit $rc"

#define WSL_DETECT_CMD \
    "eval $(opam env) 2>/dev/null; command -v frama-c; " \
    "frama-c -version 2>/dev/null"

/* Template native POSIX (Linux, tanpa WSL). Source via stdin
 * ke shell yang menjalankan frama-c langsung. */
#define NATIVE_PROVE_CMD \
    "t=/tmp/myc_prove_$$.c; cat > $t; " \
    "frama-c -eva $t; rc=$?; rm -f $t; exit $rc"

#define NATIVE_DETECT_CMD \
    "command -v frama-c; frama-c -version 2>/dev/null"

/* Parse versi Frama-C dari output DETECT ("command -v frama-c; "
 * "frama-c -version"): ambil baris pertama yang memuat pola digit.titik.digit
 * (mis. "33.0 (Arsenic)"). Disimpan ke arena hasil (MYC-AUDIT-013: laporan
 * jujur harus menyebut tool + versi, bukan sekadar label). */
static void parse_detect_version(myc_result *res, const char *text)
{
    const char *p = text;
    if (!p)
        return;
    while (p && *p) {
        const char *eol = strchr(p, '\n');
        size_t      n = eol ? (size_t)(eol - p) : strlen(p);
        const char *q = p;
        int         has_version = 0;
        while (q + 2 < p + n) {
            if (*q >= '0' && *q <= '9' && q[1] == '.' &&
                q[2] >= '0' && q[2] <= '9') {
                has_version = 1;
                break;
            }
            q++;
        }
        if (has_version) {
            while (n > 0 && (p[n - 1] == '\r' || p[n - 1] == ' ' ||
                             p[n - 1] == '\n'))
                n--;
            if (n > 0)
                res->prove_version = myc_result_arena_dup(res, p, n);
            return;
        }
        if (!eol)
            break;
        p = eol + 1;
    }
}

/* Tambah diagnostic ringan (string disalin ke pool statis bergilir). */
static void add_diag_prove(myc_result *res, const char *msg)
{
    char *slot;
    if (res->diag_count >= MYC_MAX_DIAGNOSTICS)
        return;
    slot = myc_result_arena_dup(res, msg, 0);
    if (!slot)
        return;
    res->diags[res->diag_count].line = 0;
    res->diags[res->diag_count].col = 0;
    res->diags[res->diag_count].message = slot;
    /* fakta Eva = bukti semantik (MYC-AUDIT-014) */
    res->diags[res->diag_count].confidence = MYC_CONF_CONFIRMED;
    res->diag_count++;
}

#ifdef _WIN32
/* Jalankan perintah WSL via proc.c; 1 sukses, 0 gagal (res->err diisi). */
static int run_wsl(const myc_request *req, const char *wsl_path,
                   const char *cmd, const void *stdin_data, size_t stdin_len,
                   size_t max_out, myc_proc_result *pr)
{
    const char *argv[6];
    myc_proc_request preq;
    int              n = 0;

    argv[n++] = wsl_path;
    argv[n++] = "-e";
    argv[n++] = "bash";
    argv[n++] = "-lc";
    argv[n++] = cmd;
    argv[n] = NULL;

    memset(&preq, 0, sizeof(preq));
    preq.argv = argv;
    preq.cwd = req->cwd;
    preq.stdin_data = stdin_data;
    preq.stdin_len = stdin_len;
    preq.timeout_ms = req->timeout_ms;
    preq.max_output_bytes = max_out;
    return myc_proc_run(&preq, pr);
}
#endif

/* Ambil baris alarm dari output Eva: "[eva:alarm]" -> diagnostic; hitung. */
static int ingest_eva_alarms(myc_result *res, const char *text)
{
    int count = 0;
    const char *p = text;
    if (!text)
        return 0;
    while ((p = strstr(p, "[eva:alarm]")) != NULL) {
        /* baris alarm: "[eva:alarm] <file>:<line>: Warning: <msg>" */
        const char *line_start = p;
        const char *nl;
        const char *msg = p + strlen("[eva:alarm]");
        char        note[512];
        int         line = 0;
        while (line_start > text && line_start[-1] != '\n')
            line_start--;
        nl = strchr(p, '\n');
        if (nl && nl < line_start + 512) {
            size_t n = (size_t)(nl - msg);
            if (n > 400)
                n = 400;
            snprintf(note, sizeof(note), "prove: Eva alarm: %.*s", (int)n, msg);
        } else {
            snprintf(note, sizeof(note), "prove: Eva alarm");
        }
        /* parse line number "file.c:NNN:" bila ada di awal msg */
        {
            const char *q = msg;
            while (q && *q && *q != ':')
                q++;
            if (q && *q == ':') {
                char *end = NULL;
                long  ln = strtol(q + 1, &end, 10);
                if (end && *end == ':' && ln > 0 && ln < 100000)
                    line = (int)ln;
            }
        }
        if (res->diag_count < MYC_MAX_DIAGNOSTICS) {
            char *slot = myc_result_arena_dup(res, note, 0);
            if (!slot)
                break;
            res->diags[res->diag_count].line = line;
            res->diags[res->diag_count].col = 0;
            res->diags[res->diag_count].message = slot;
            /* alarm Eva = bukti semantik (MYC-AUDIT-014) */
            res->diags[res->diag_count].confidence = MYC_CONF_CONFIRMED;
            res->diag_count++;
        }
        count++;
        p += strlen("[eva:alarm]");
        if (count >= 1000)
            break;
    }
    return count;
}

/* Coba parse output JSON Frama-C (jika tersedia).
 * Mengembalikan jumlah alarm yang ditemukan, atau -1 bila bukan JSON. */
static int ingest_eva_json(myc_result *res, const char *text)
{
    const char *p = text;
    int         count = 0;
    if (!text)
        return -1;
    /* JSON Eva dimulai dengan "[" atau "{". */
    while (*p && (*p == ' ' || *p == '\t' || *p == '\n' || *p == '\r'))
        p++;
    if (*p != '[' && *p != '{')
        return -1;
    /* Cari "[eva:alarm]" di JSON juga (Frama-C menyematkan marker yang sama). */
    count = ingest_eva_alarms(res, text);
    return count >= 0 ? count : -1;
}

/* Hitung alarm Eva dari output: preferensi output mesin (JSON) bila
 * tersedia, fallback ke pemindaian teks baris "[eva:alarm]"
 * (Task 10: machine output if available — Frama-C). */
static int count_eva_alarms(myc_result *res, const char *text)
{
    int a = ingest_eva_json(res, text);
    if (a >= 0)
        return a;
    return ingest_eva_alarms(res, text);
}

/* Hitung proof obligation dari output Eva.
 * Mengembalikan jumlah yang ditemukan (0 jika tidak ditemukan). */
static int count_proof_obligations(const char *text)
{
    int count = 0;
    const char *p = text;
    if (!text)
        return 0;
    while ((p = strstr(p, "proof obligation")) != NULL) {
        count++;
        p += strlen("proof obligation");
        if (count >= 10000)
            break;
    }
    return count;
}

int myc_prove_gate(const myc_request *req, const char *source, size_t source_len,
                    myc_result *res)
{
    size_t max_out = req->max_output_bytes > 0
                         ? (size_t)req->max_output_bytes
                         : MYC_MAX_OUTPUT_BYTES;
    myc_proc_result pres;
    int   alarms = 0;

    myc_gate_set_status(res, MYC_GATE_PROVE, MYC_GATE_NOT_APPLICABLE, NULL);

#ifdef _WIN32
    /* Windows: cari wsl.exe, jalankan frama-c via WSL. */
    char *wsl_path = NULL;
    if (!wsl_path) {
        add_diag_prove(res, "gate Eva di-skip: wsl.exe tidak ditemukan "
                            "(Frama-C hanya tersedia via WSL di Windows)");
        myc_gate_set_status(res, MYC_GATE_PROVE, MYC_GATE_UNAVAILABLE,
                            "wsl.exe tidak ditemukan");
        myc_result_add_evidence(res, MYC_GATE_PROVE, MYC_EVIDENCE_SKIP,
                                "Eva di-skip: wsl.exe hilang");
        return 0;
    }
#else
    /* POSIX native: cari frama-c langsung di PATH. */
    char *frama_path = NULL;
    frama_path = myc_find_executable("frama-c");
    if (!frama_path) {
        add_diag_prove(res, "gate Eva di-skip: frama-c tidak ditemukan "
                            "di PATH (instal: opam install -y frama-c)");
        myc_gate_set_status(res, MYC_GATE_PROVE, MYC_GATE_UNAVAILABLE,
                            "frama-c tidak ditemukan di PATH");
        myc_result_add_evidence(res, MYC_GATE_PROVE, MYC_EVIDENCE_SKIP,
                                "Eva di-skip: frama-c hilang");
        return 0;
    }
#endif

    #ifdef _WIN32
    /* 2. Deteksi frama-c di dalam WSL. */
    memset(&pres, 0, sizeof(pres));
    if (!run_wsl(req, wsl_path, WSL_DETECT_CMD, NULL, 0, 65536, &pres)) {
        if (pres.timed_out) {
            res->verdict = MC_TIMEOUT;
            res->err = MYC_ERR_TIMEOUT;
            res->duration_ms += pres.duration_ms;
            myc_proc_result_free(&pres);
            myc_free(wsl_path);
            myc_gate_set_status(res, MYC_GATE_PROVE, MYC_GATE_INCONCLUSIVE,
                                "detect frama-c timeout");
            myc_result_add_evidence(res, MYC_GATE_PROVE, MYC_EVIDENCE_ERROR,
                                    "Eva detect timeout");
            return 0;
        }
        add_diag_prove(res, "gate Eva di-skip: gagal memeriksa frama-c di WSL");
        myc_gate_set_status(res, MYC_GATE_PROVE, MYC_GATE_INFRA_FAILED,
                            "gagal memeriksa frama-c di WSL");
        myc_result_add_evidence(res, MYC_GATE_PROVE, MYC_EVIDENCE_ERROR,
                                "Eva detect infra failed");
        myc_proc_result_free(&pres);
        myc_free(wsl_path);
        return 0;
    }
    res->duration_ms += pres.duration_ms;
    if (pres.timed_out) {
        res->verdict = MC_TIMEOUT;
        res->err = MYC_ERR_TIMEOUT;
        myc_proc_result_free(&pres);
        myc_free(wsl_path);
        myc_gate_set_status(res, MYC_GATE_PROVE, MYC_GATE_INCONCLUSIVE,
                            "detect frama-c timeout");
        myc_result_add_evidence(res, MYC_GATE_PROVE, MYC_EVIDENCE_ERROR,
                                "Eva detect timeout");
        return 0;
    }
    if (pres.exit_code != 0 ||
        !(pres.stdout_data && strstr(pres.stdout_data, "frama-c"))) {
        add_diag_prove(res, "gate Eva di-skip: frama-c tidak ditemukan di WSL "
                            "(instal: opam install -y frama-c)");
        myc_gate_set_status(res, MYC_GATE_PROVE, MYC_GATE_UNAVAILABLE,
                            "frama-c tidak ditemukan di WSL");
        myc_result_add_evidence(res, MYC_GATE_PROVE, MYC_EVIDENCE_SKIP,
                                "Eva di-skip: frama-c hilang");
        myc_proc_result_free(&pres);
        myc_free(wsl_path);
        return 0;
    }
    parse_detect_version(res, pres.stdout_data);
    myc_proc_result_free(&pres);

    /* 3. Jalankan Eva; source via stdin ke template WSL. */
    memset(&pres, 0, sizeof(pres));
    if (!run_wsl(req, wsl_path, WSL_PROVE_CMD, source, source_len,
                 max_out, &pres)) {
        if (pres.timed_out) {
            res->verdict = MC_TIMEOUT;
            res->err = MYC_ERR_TIMEOUT;
            res->duration_ms += pres.duration_ms;
            myc_proc_result_free(&pres);
            myc_free(wsl_path);
            myc_gate_set_status(res, MYC_GATE_PROVE, MYC_GATE_INCONCLUSIVE,
                                "frama-c -eva timeout");
            myc_result_add_evidence(res, MYC_GATE_PROVE, MYC_EVIDENCE_ERROR,
                                    "Eva timeout");
            return 0;
        }
        add_diag_prove(res, "gate Eva di-skip: gagal menjalankan frama-c -eva");
        myc_gate_set_status(res, MYC_GATE_PROVE, MYC_GATE_INFRA_FAILED,
                            "gagal menjalankan frama-c -eva");
        myc_result_add_evidence(res, MYC_GATE_PROVE, MYC_EVIDENCE_ERROR,
                                "Eva exec failed");
        myc_proc_result_free(&pres);
        myc_free(wsl_path);
        return 0;
    }
    res->duration_ms += pres.duration_ms;
    if (pres.timed_out) {
        res->verdict = MC_TIMEOUT;
        res->err = MYC_ERR_TIMEOUT;
        myc_proc_result_free(&pres);
        myc_free(wsl_path);
        myc_gate_set_status(res, MYC_GATE_PROVE, MYC_GATE_INCONCLUSIVE,
                            "frama-c -eva timeout");
        myc_result_add_evidence(res, MYC_GATE_PROVE, MYC_EVIDENCE_ERROR,
                                "Eva timeout");
        return 0;
    }
    {
        int eva_exit = pres.exit_code;
        myc_free(res->prove_stdout_text);
        myc_free(res->prove_stderr_text);
        res->prove_stdout_text = pres.stdout_data; pres.stdout_data = NULL;
        res->prove_stderr_text = pres.stderr_data; pres.stderr_data = NULL;
        myc_proc_result_free(&pres);
        res->ran_prove = 1;
        res->prove_mode = "eva (abstract interpretation)";
        if (eva_exit != 0) {
            char note[512];
            const char *fe = res->prove_stderr_text && res->prove_stderr_text[0]
                                 ? res->prove_stderr_text
                                 : "frama-c -eva gagal (lihat output)";
            if (strlen(fe) > 400)
                snprintf(note, sizeof(note), "gate Eva di-skip: %.*s...", 400, fe);
            else
                snprintf(note, sizeof(note), "gate Eva di-skip: %s", fe);
            add_diag_prove(res, note);
            myc_gate_set_status(res, MYC_GATE_PROVE, MYC_GATE_INCONCLUSIVE, note);
            myc_result_add_evidence(res, MYC_GATE_PROVE, MYC_EVIDENCE_SKIP, note);
            myc_free(wsl_path);
            return 0;
        }
        alarms = count_eva_alarms(res, res->prove_stdout_text);
        alarms += count_eva_alarms(res, res->prove_stderr_text);
        res->prove_alarms = alarms;
        res->prove_proof_obligations =
            count_proof_obligations(res->prove_stdout_text) +
            count_proof_obligations(res->prove_stderr_text);
        if (alarms > 0) {
            char note[128];
            snprintf(note, sizeof(note),
                     "prove: Eva menemukan %d alarm RTE (kelas RTE = bug pasti)",
                     alarms);
            add_diag_prove(res, note);
            res->verdict = MC_PROVE_VIOLATION;
            res->err = MYC_ERR_PROVE_VIOLATION;
            myc_gate_set_status(res, MYC_GATE_PROVE, MYC_GATE_COMPLETED_FINDINGS,
                                note);
            myc_result_add_evidence(res, MYC_GATE_PROVE, MYC_EVIDENCE_FINDING, note);
            /* Isi witness dari Eva (Fase 1). */
            if (!res->witness) {
                res->witness = (myc_witness *)myc_malloc(sizeof(myc_witness));
                if (res->witness) {
                    myc_witness_init(res->witness);
                    res->witness->violation_kind =
                        myc_result_arena_dup(res, "rte-alarm", 0);
                    res->witness->violation_msg =
                        myc_result_arena_dup(res, note, 0);
                    res->witness->backend =
                        myc_result_arena_dup(res, "eva", 0);
                    res->witness->operation =
                        myc_result_arena_dup(res, note, 0);
                    res->witness->pre_state =
                        myc_result_arena_dup(res, "Eva precondition check", 0);
                }
            }
            myc_free(wsl_path);
            return 0;
        }
        if (!(res->prove_stdout_text &&
              strstr(res->prove_stdout_text, "ANALYSIS SUMMARY"))) {
            add_diag_prove(res, "gate Eva di-skip: Eva tidak menganalisis apa pun "
                                "(tidak ada summary) - assurance statis dipertahankan");
            myc_gate_set_status(res, MYC_GATE_PROVE, MYC_GATE_NOT_APPLICABLE,
                                "Eva tidak menganalisis (no summary)");
            myc_result_add_evidence(res, MYC_GATE_PROVE, MYC_EVIDENCE_SKIP,
                                    "Eva di-skip: tidak ada ANALYSIS SUMMARY");
            myc_free(wsl_path);
            return 0;
        }
        add_diag_prove(res, "prove: Eva 0 alarm RTE (abstract interpretation, "
                            "entry main; bukan proof obligation WP)");
        myc_gate_set_status(res, MYC_GATE_PROVE, MYC_GATE_COMPLETED_CLEAN,
                            "Eva 0 alarm + summary");
        myc_result_add_evidence(res, MYC_GATE_PROVE, MYC_EVIDENCE_GATE_END,
                                "Frama-C Eva clean");
        myc_free(wsl_path);
        return 1;
    }
#else
    /* POSIX native: frama-c langsung di PATH. */
    /* 2. Deteksi versi frama-c. */
    {
        const char *detect_argv[] = { "frama-c", "-version", NULL };
        myc_proc_request preq = { detect_argv, NULL, NULL, 0, 30000, max_out, NULL };
        memset(&pres, 0, sizeof(pres));
        if (!myc_proc_run(&preq, &pres)) {
            if (pres.timed_out) {
                res->verdict = MC_TIMEOUT;
                res->err = MYC_ERR_TIMEOUT;
                res->duration_ms += pres.duration_ms;
                myc_proc_result_free(&pres);
                myc_free(frama_path);
                myc_gate_set_status(res, MYC_GATE_PROVE, MYC_GATE_INCONCLUSIVE,
                                    "frama-c version timeout");
                myc_result_add_evidence(res, MYC_GATE_PROVE, MYC_EVIDENCE_ERROR,
                                        "frama-c version timeout");
                return 0;
            }
            add_diag_prove(res, "gate Eva di-skip: gagal menjalankan frama-c -version");
            myc_gate_set_status(res, MYC_GATE_PROVE, MYC_GATE_INFRA_FAILED,
                                "gagal menjalankan frama-c -version");
            myc_result_add_evidence(res, MYC_GATE_PROVE, MYC_EVIDENCE_ERROR,
                                    "frama-c version exec failed");
            myc_proc_result_free(&pres);
            myc_free(frama_path);
            return 0;
        }
        res->duration_ms += pres.duration_ms;
        if (pres.exit_code != 0 ||
            !(pres.stdout_data && strstr(pres.stdout_data, "frama-c"))) {
            add_diag_prove(res, "gate Eva di-skip: frama-c tidak ditemukan di PATH "
                                "(instal: opam install -y frama-c)");
            myc_gate_set_status(res, MYC_GATE_PROVE, MYC_GATE_UNAVAILABLE,
                                "frama-c tidak ditemukan di PATH");
            myc_result_add_evidence(res, MYC_GATE_PROVE, MYC_EVIDENCE_SKIP,
                                    "Eva di-skip: frama-c hilang");
            myc_proc_result_free(&pres);
            myc_free(frama_path);
            return 0;
        }
        parse_detect_version(res, pres.stdout_data);
        myc_proc_result_free(&pres);
    }

    /* 3. Jalankan Eva; source via stdin ke template native. */
    {
        const char *eva_argv[] = { "frama-c", "-eva", NULL };
        myc_proc_request preq = { eva_argv, NULL, source, source_len, 30000, max_out, NULL };
        memset(&pres, 0, sizeof(pres));
        if (!myc_proc_run(&preq, &pres)) {
            if (pres.timed_out) {
                res->verdict = MC_TIMEOUT;
                res->err = MYC_ERR_TIMEOUT;
                res->duration_ms += pres.duration_ms;
                myc_proc_result_free(&pres);
                myc_free(frama_path);
                myc_gate_set_status(res, MYC_GATE_PROVE, MYC_GATE_INCONCLUSIVE,
                                    "frama-c -eva timeout");
                myc_result_add_evidence(res, MYC_GATE_PROVE, MYC_EVIDENCE_ERROR,
                                        "Eva timeout");
                return 0;
            }
            add_diag_prove(res, "gate Eva di-skip: gagal menjalankan frama-c -eva");
            myc_gate_set_status(res, MYC_GATE_PROVE, MYC_GATE_INFRA_FAILED,
                                "gagal menjalankan frama-c -eva");
            myc_result_add_evidence(res, MYC_GATE_PROVE, MYC_EVIDENCE_ERROR,
                                    "Eva exec failed");
            myc_proc_result_free(&pres);
            myc_free(frama_path);
            return 0;
        }
        res->duration_ms += pres.duration_ms;
        if (pres.exit_code != 0) {
            alarms = count_eva_alarms(res, pres.stdout_data);
            res->prove_proof_obligations =
                count_proof_obligations(pres.stdout_data) +
                count_proof_obligations(pres.stderr_data);
            if (alarms > 0) {
                res->verdict = MC_PROVE_VIOLATION;
                res->err = MYC_ERR_NONE;
                add_diag_prove(res, "prove: Eva menemukan alarm RTE "
                                    "(bug memori potensial)");
                myc_gate_set_status(res, MYC_GATE_PROVE, MYC_GATE_COMPLETED_FINDINGS,
                                    "Eva alarm");
                myc_result_add_evidence(res, MYC_GATE_PROVE, MYC_EVIDENCE_FINDING,
                                        "Eva alarm RTE terdeteksi");
            } else {
                add_diag_prove(res, "frama-c -eva exit != 0 tanpa alarm "
                                    "(infra/gagal parse)");
                myc_gate_set_status(res, MYC_GATE_PROVE, MYC_GATE_INCONCLUSIVE,
                                    "frama-c exit != 0 tanpa alarm");
                myc_result_add_evidence(res, MYC_GATE_PROVE, MYC_EVIDENCE_ERROR,
                                        "Eva exit != 0 tanpa alarm terdeteksi");
            }
        } else {
            alarms = count_eva_alarms(res, pres.stdout_data);
            res->prove_proof_obligations =
                count_proof_obligations(pres.stdout_data) +
                count_proof_obligations(pres.stderr_data);
            /* PR-009 (INV-001): exit 0 + 0 alarm BUKAN otomatis clean —
             * output malformed (garbage tanpa ANALYSIS SUMMARY) TIDAK boleh
             * dipromosikan menjadi clean. Konsisten dengan jalur WSL yang
             * mengecek "ANALYSIS SUMMARY" sebelum COMPLETED_CLEAN. */
            if (alarms == 0) {
                if (pres.stdout_data &&
                    strstr(pres.stdout_data, "ANALYSIS SUMMARY")) {
                    res->verdict = MC_OK;
                    res->err = MYC_ERR_NONE;
                    add_diag_prove(res, "prove: Eva 0 alarm RTE (abstract "
                                        "interpretation, entry main; bukan "
                                        "proof obligation WP)");
                    myc_gate_set_status(res, MYC_GATE_PROVE,
                                        MYC_GATE_COMPLETED_CLEAN,
                                        "Eva 0 alarm + summary");
                    myc_result_add_evidence(res, MYC_GATE_PROVE,
                                            MYC_EVIDENCE_CLEAN,
                                            "Eva 0 alarm RTE + summary");
                } else {
                    /* output malformed/tanpa summary: bukan bukti bersih.
                     * Gate di-skip (NOT_APPLICABLE), bukan clean palsu. */
                    add_diag_prove(res, "gate Eva di-skip: output frama-c "
                                        "tidak memuat ANALYSIS SUMMARY "
                                        "(malformed/tidak menganalisis) - "
                                        "assurance statis dipertahankan");
                    myc_gate_set_status(res, MYC_GATE_PROVE,
                                        MYC_GATE_NOT_APPLICABLE,
                                        "Eva tanpa summary (output malformed)");
                    myc_result_add_evidence(res, MYC_GATE_PROVE,
                                            MYC_EVIDENCE_SKIP,
                                            "Eva di-skip: tanpa ANALYSIS "
                                            "SUMMARY (INV-001)");
                }
            } else {
                res->verdict = MC_PROVE_VIOLATION;
                res->err = MYC_ERR_NONE;
                add_diag_prove(res, "prove: Eva menemukan alarm RTE "
                                    "(bug memori potensial)");
                myc_gate_set_status(res, MYC_GATE_PROVE, MYC_GATE_COMPLETED_FINDINGS,
                                    "Eva alarm");
                myc_result_add_evidence(res, MYC_GATE_PROVE, MYC_EVIDENCE_FINDING,
                                        "Eva alarm RTE terdeteksi");
            }
        }
        myc_free(frama_path);
        return 1;
    }
#endif
}
