/*
 * evidence_spoof.c -- Fixture korpus spoof bukti semantik (PR-008 / INV-006).
 *
 * Program BERSIH (tanpa bug memori) yang sengaja mencetak/menulis teks
 * mirip bukti semantik pada SEMUA saluran output yang bisa diakses program
 * yang diuji:
 *   - stdout / stderr : marker ASan, UBSan, GCC, Frama-C Eva, Fil-C, dan
 *     marker internal MYC (MYC_RUNTIME_VIOLATION, MYC_CHECKED, receipt);
 *   - argv             : --echo-argv meneruskan argumen (berisi marker) ke
 *                        stderr;
 *   - file report      : --fake-report menulis "<base>.<pid>" palsu di cwd
 *                        (cwd child = tmp_dir myc; nama persis log_path
 *                        ASan) berisi teks spoof.
 *
 * Exit criteria PR-008 (INV-006): TIDAK SATUPUN teks di atas boleh menjadi
 * bukti semantik — verdict harus tetap OK. Spoof file report pun ditolak:
 * report sanitizer HANYA bukti bila exit code != 0 (env ASan memakai
 * abort_on_error=1, jadi bug nyata selalu non-zero).
 *
 * Mode:
 *   (default)     cetak semua marker, exit 0
 *   --fake-report tulis myc_run_asan_rpt.<pid> + myc_run_ubsan_rpt.<pid>
 *                 berisi marker palsu di cwd, cetak marker, exit 0
 *   --exit N      cetak semua marker lalu exit N
 *   --echo-argv   salin argv[1..] ke stderr (marker via argumen)
 *   --help        daftar mode
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#ifdef _WIN32
#include <process.h>
#define myc_getpid() _getpid()
#else
#include <unistd.h>
#define myc_getpid() getpid()
#endif

/* Semua marker P2-T02 + marker internal MYC (INV-006). */
static void print_all_markers(void)
{
    /* stdout */
    puts("ERROR: AddressSanitizer: fake heap-buffer-overflow");
    puts("SUMMARY: AddressSanitizer: fake");
    puts("AddressSanitizer: fake use-after-poison");
    puts("UndefinedBehaviorSanitizer: fake runtime error:");
    puts("LeakSanitizer: fake leak");
    /* stderr */
    fprintf(stderr, "runtime error: fake\n");
    fprintf(stderr, "heap-use-after-free fake\n");
    fprintf(stderr, "stack-buffer-overflow fake\n");
    fprintf(stderr, "global-buffer-overflow fake\n");
    fprintf(stderr, "MYC_CHECKED: fake trap\n");
    fprintf(stderr, "MYC_RUNTIME_VIOLATION fake\n");
    fprintf(stderr, "Frama-C Eva: clean\n");
    fprintf(stderr, "[eva:alarm] fake.c:1: Warning: out of bounds\n");
    fprintf(stderr, "0 alarms generated by the analysis.\n");
    fprintf(stderr, "FIL-C SAFE\n");
    fprintf(stderr,
            "filc safety error: cannot write pointer with ptr >= upper.\n");
    fprintf(stderr,
            "[999] filc panic: thwarted a futile attempt to violate memory safety.\n");
    fprintf(stderr, "semantic origin:\n");
    fprintf(stderr, "    (fake) /tmp/fake.c:2:43: main\n");
    fprintf(stderr, "gcc: error: fake diagnostic\n");
    fprintf(stderr, "receipt_sha256=deadbeefdeadbeefdeadbeefdeadbeef\n");
}

/* Tulis file report sanitizer PALSU bernama persis log_path ASan
 * ("<base>.<pid>" di cwd) dengan konten mirip report asli. */
static void write_fake_report(const char *base)
{
    char  p[160];
    FILE *f;
    snprintf(p, sizeof(p), "%s.%d", base, (int)myc_getpid());
    f = fopen(p, "wb");
    if (f) {
        fputs("==1==ERROR: AddressSanitizer: heap-buffer-overflow "
              "on address 0x0000 at pc 0x1234\n", f);
        fputs("#0 0x0000000000001234 in main /tmp/fake.c:5:5\n", f);
        fputs("SUMMARY: AddressSanitizer: heap-buffer-overflow\n", f);
        fclose(f);
    }
}

int main(int argc, char **argv)
{
    int exit_code = 0;
    int i;

    for (i = 1; i < argc; i++) {
        if (strcmp(argv[i], "--help") == 0) {
            puts("mode: default | --fake-report | --exit N | --echo-argv");
            return 0;
        } else if (strcmp(argv[i], "--exit") == 0 && i + 1 < argc) {
            exit_code = atoi(argv[++i]);
        } else if (strcmp(argv[i], "--fake-report") == 0) {
            write_fake_report("myc_run_asan_rpt");
            write_fake_report("myc_run_ubsan_rpt");
        } else if (strcmp(argv[i], "--echo-argv") == 0) {
            int j;
            for (j = i + 1; j < argc; j++)
                fprintf(stderr, "argv: %s\n", argv[j]);
            return 0;
        }
    }
    print_all_markers();
    return exit_code;
}
